## ¿Qué es el Feature Engineering y por qué es crítico?


Es el proceso de transformar los datos crudos en variables que un modelo de ML puede entender y aprovechar.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.feature_selection import SelectKBest, f_regression, f_classif

In [4]:
df = pd.read_csv("SampleSuperstore.csv", encoding='latin1')

cols_utiles = ['Ship Mode', 'Segment', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit']

df = df[cols_utiles].copy()

df.head(5)

,Ship Mode,Segment,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

## Encoding de variables categóricas..

Label Encoding = Un número por categoría (0,1,2) -----> 2 > 1 > 0

One Hot Encoding = Una columna binaria por categoría

Ordinal Encoding = Un número por categoría respetando el orden real ----> Categoría definida

In [6]:
#Label Encoding, Asigna un número enteero por cata categoría.

#¿Cuando es correcto es usarlo? (Malo < Regular < Bueno) o prioridad (Baja < Media < Alta)

l_encoding = LabelEncoder()

#Resultado: Central->0    , East->1        , South->2          ,west->3
df['Region_label'] = l_encoding.fit_transform(df['Region'])


mapeo_label = dict(zip(l_encoding.classes_,l_encoding.transform(l_encoding.classes_)))

#Resultado o Mapeo

print('Mapeo Label Encoding - Region:', mapeo_label)
print()
print('Problema: El modelo va a interpretar West(3) > South(2) > East(1) > Central(0)')

Mapeo Label Encoding - Region: {'Central': np.int64(0), 'East': np.int64(1), 'South': np.int64(2), 'West': np.int64(3)}

Problema: El modelo va a interpretar West(3) > South(2) > East(1) > Central(0)

In [ ]:
#Ordinal Encoding -> Este también produce un númeor por categoría, pero permite especificar el orden correcto tú mismo

orden_envio = [['Standard Class', 'Second Class', 'First Class', 'Same Day']]

or_encoder = OrdinalEncoder(categories=orden_envio)

df['Ship_Mode_ordinal'] = or_encoder.fit_transform(df[['Ship Mode']]).reshape(-1)

#Verfiy

df[['Ship Mode', 'Ship_Mode_ordinal']].drop_duplicates().sort_values('Ship_Mode_ordinal')

          Ship Mode  Ship_Mode_ordinal
3    Standard Class                0.0
0      Second Class                1.0
35      First Class                2.0
366        Same Day                3.0

In [11]:
#One Hot Encoding con pd.get_dummies = Es crear una columna binaria por cada categoría. Si un registro pertenece a esa categoria, la columna vale = 1, sino vale = 0.

df_ohe = pd.get_dummies(
    df,
    columns=['Segment', 'Region', 'Category'],
    drop_first=True, #Eliminar la primera categoría de cada variable
    dtype=int          #binario
)

cols_nuevas = [c for c in df_ohe.columns if c.startswith(('Segment_', 'Region_', 'Category_'))]

df_ohe[cols_nuevas].head(8)

,Region_label,Segment_Corporate,Segment_Home Office,Region_East,Region_South,Region_West,Category_Office Supplies,Category_Technology
0,2,0,0,0,1,0,0,0
1,2,0,0,0,1,0,0,0
2,3,1,0,0,0,1,1,0
3,2,0,0,0,1,0,0,0
4,2,0,0,0,1,0,1,0
5,3,0,0,0,0,1,0,0
6,3,0,0,0,0,1,1,0
7,3,0,0,0,0,1,0,1