## Librerías

In [2]:
import pandas as pd
import numpy as np

#Nos permite trabajar y construie visualizaciones base
import matplotlib.pyplot as plt

#Nos permite construir visualizaciones estadísticas de alto nivel
import seaborn as sns

#Herramienta de escalado estandar
from sklearn.preprocessing import StandardScaler

print("Ok")

Ok

In [3]:
#Carga del dataset
df = pd.read_csv("SampleSuperstore.csv", encoding='latin-1')


df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [4]:
#Dimensiones del dataset (shape)

filas, columnas = df.shape

print(f"El dataset tiene {filas:,} registros y {columnas} variables")

El dataset tiene 9,994 registros y 13 variables

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1.7 MB

In [8]:
df.describe().round(2)

       Postal Code     Sales  Quantity  Discount   Profit
count      9994.00   9994.00   9994.00   9994.00  9994.00
mean      55190.38    229.86      3.79      0.16    28.66
std       32063.69    623.25      2.23      0.21   234.26
min        1040.00      0.44      1.00      0.00 -6599.98
25%       23223.00     17.28      2.00      0.00     1.73
50%       56430.50     54.49      3.00      0.20     8.67
75%       90008.00    209.94      5.00      0.20    29.36
max       99301.00  22638.48     14.00      0.80  8399.98

In [10]:
#¿Realmente hay nulos o no?

nulos_por_columna = df.isnull().sum()

nulos_por_columna

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [12]:
total_duplicados = df.duplicated().sum()

total_duplicados

np.int64(17)

In [13]:
#Variablkes categóricas que queremos revisar

variables_categoricas = ["Ship Mode", "Segment", "Region", "Category", "Sub-Category"]

for col in variables_categoricas:
    valores = df[col].unique()
    
    print(f"\n {col} -> {len(valores)} categorías")
    print(f" {list(valores)}")

 Ship Mode -> 4 categorías
 ['Second Class', 'Standard Class', 'First Class', 'Same Day']

 Segment -> 3 categorías
 ['Consumer', 'Corporate', 'Home Office']

 Region -> 4 categorías
 ['South', 'West', 'Central', 'East']

 Category -> 3 categorías
 ['Furniture', 'Office Supplies', 'Technology']

 Sub-Category -> 17 categorías
 ['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage', 'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper', 'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines', 'Copiers']

Escalado de Variables: