## ML con Regresión Logística

Rama de la IA que enseña a la maquinas o computdoras a aprender de los datos sin ser programados.


Datos + Respuestas -------------> El modelo aprender las reglas por sí solo


Clasificación ---> Regresión logísticas: Predecir una categorías ( Apreuab o reprueba)

In [1]:
#Liberías e Importaciones

import pandas as pd
import numpy as np

#Visualización
import matplotlib.pyplot as plt
import seaborn as sns

#Modelos de Marchine Learning
from sklearn.linear_model import LinearRegression, LogisticRegression

#train_test_split: Dividir el dataset en datos de entrenamiento y prueba de forma aleatoria y controlada
from sklearn.model_selection import train_test_split

#StarndarScaler
#OrdinalEncoder: Codifique variables categoricas con orden real
from sklearn.preprocessing import StandardScaler, OrdinalEncoder

#Metricas de evaluación para regresión
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#Clasificación
from sklearn.metrics import (accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay)

In [5]:
#Carga de datos y lectura

df = pd.read_csv("student_habits_performance.csv")

df = df.drop(columns=['student_id'])

df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [7]:
df['aprueba'] = (df['exam_score'] >=60).astype(int)

df['aprueba'].value_counts(normalize=True).round(3)

aprueba
1    0.72
0    0.28
Name: proportion, dtype: float64

In [10]:
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,aprueba
0,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2,0
1,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0,1
2,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3,0
3,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8,0
4,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4,1

## Tratamiento de Nulos

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1000 non-null   int64
 1   gender                         1000 non-null   str
 2   study_hours_per_day            1000 non-null   float64
 3   social_media_hours             1000 non-null   float64
 4   netflix_hours                  1000 non-null   float64
 5   part_time_job                  1000 non-null   str
 6   attendance_percentage          1000 non-null   float64
 7   sleep_hours                    1000 non-null   float64
 8   diet_quality                   1000 non-null   str
 9   exercise_frequency             1000 non-null   int64
 10  parental_education_level       909 non-null    str
 11  internet_quality               1000 non-null   str
 12  mental_health_rating           1000 non-null   int64
 13  extracurricular_participation  1000 non-null   str
 14  exam_score                     1000 non-null   float64
 15  aprueba                        1000 non-null   int64
dtypes: float64(6), int64(4), str(6)
memory usage: 151.4 KB